services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    pull_policy: never
    container_name: ft_transcendence_api
    ports:
      - "4001:4001"
    working_dir: /app/apps/api
    volumes:
      - ./apps/api:/app/apps/api
      - games-data:/app/data
    environment:
      - PORT=4001
      - DB_DIR=/app/data

volumes:
  games-data:
