global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['ft_api:4001']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ft_node_exporter:9100']

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
